### ISSUE TITLE
vagrant基本指南 | catccc

### ISSUE THREAD

**Issue by chengzyzy** [CatCccC/catcccc.github.io#1]
https://catcccc.github.io/2019/04/:linux/vagrant%E5%9F%BA%E6%9C%AC%E6%8C%87%E5%8D%97/#comments 

 安装vagrant和virtual box vagrant 下载目录  virtualbox 下载目录  安装插件 1vagrant plugin install vagrant-vbguest --plugin-clean-sources --plugin-source https://gems.ruby-china.com/   安装开发环境Vagrant的基本单元叫做box，我们可以理解为镜

**Comment by CatCccC** [comment]
测试一下

**Comment by chengzyzy** [comment]
测试
